- name: "Clear cache"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Force restart of varnish"
      service: name="varnish" state="restarted" enabled="yes"
- name: "Run Benchmarks"
  hosts: vcpbench-consumer*
  tasks:
    - name: "Run vegeta reference test (one hit url only for 10 seconds)"
      shell: echo "GET http://loadbalancer/reference/?content-length&max-age=6000&header-delay=100predictable-content=202502" | /usr/local/bin/vegeta attack -duration=10s -rate 100 | tee results.bin | vegeta report 
      register: testresult
    - debug: var=testresult.stdout_lines
    - name: "Run vegeta varnish cache plus test (4 minutes)"
      shell: /usr/local/bin/vegeta -cpus 4 -profile cpu attack -duration=240s -rate 100 -targets /tmp/targets.txt
      register: testresult
    - debug: var=testresult.stdout_lines
