- name: "Create local benchmark result directory"
  hosts: 127.0.0.1
  connection: local
  become: false
  tasks:
    - name: "Create directories"
      file: path={{ item }} state=directory
      with_items:
        - ./results
        - ./results/{{ benchmark_id }}
      become: false
- name: "Prepare varnishservers"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Force restart of varnish"
      service: name="varnish" state="restarted" enabled="yes"
- name: "Reset stats"
  hosts: vcpbench-backend
  tasks:
    - name: "Reset backend requests pre-benchmark"
      uri: url='http://localhost:8080/x-resetdummyapistatistics'
      register: backendreqs
    - debug: var=backendreqs.x_request_counter
- name: "Run Reference Test"
  hosts: vcpbench-consumer*
  tasks:
    - name: "Copy wrk url list"
      copy: src="files/urls.txt" dest="/tmp/urls.txt" mode=ugo+rwx owner=root group=root
    - name: "Warm cache"
      uri: url='http://loadbalancer/reference/?content-length&max-age=6000&header-delay=100predictable-content=200000'
      register: cachewarm
    - debug: var=cachewarm.status
    - name: "Wait for replication"
      pause: seconds=2
    - name: "Run wrk reference test (one hit url only for 10 seconds)"
      shell: /usr/local/bin/wrk -t 1 -d 10 -c 300 "http://loadbalancer/reference/?content-length&max-age=6000&header-delay=100predictable-content=200000"
      register: testresult
    - debug: var=testresult.stdout_lines
    - name: "Dump reference testresult to local file"
      become: false
      local_action: copy content="{{ testresult.stdout }}" dest=./results/{{ benchmark_id }}/reference_test_{{ vha_status }}.log
- name: "Get stats"
  hosts: vcpbench-backend
  tasks:
    - name: "Get backend requests post-reference"
      uri: url='http://localhost:8080/x-dumpdummyapistatistics'
      register: backendreqs
    - debug: var=backendreqs.x_request_counter
    - name: "Reset backend requests post-reference"
      uri: url='http://localhost:8080/x-resetdummyapistatistics'

- name: "Run Benchmark Pass 1"
  hosts: vcpbench-consumer*
  tasks:
    - include: playbook-includes/wrkbench-benchmark.yml pass=1 threads=1 duration=90 concurrency=200 
- name: "Get backend reqs Pass 1"
  hosts: vcpbench-backend
  tasks:
    - include: playbook-includes/wrkbench-collect.yml pass=1
- name: "Post process output Pass 1"
  connection: local
  hosts: 127.0.0.1
  become: false
  tasks:
    - include: playbook-includes/wrkbench-process.yml pass=1

- name: "Run Benchmark Pass 2"
  hosts: vcpbench-consumer*
  tasks:
    - include: playbook-includes/wrkbench-benchmark.yml pass=2 threads=1 duration=90 concurrency=200 
- name: "Get backend reqs Pass 2"
  hosts: vcpbench-backend
  tasks:
    - include: playbook-includes/wrkbench-collect.yml pass=2
- name: "Post process output Pass 2"
  connection: local
  hosts: 127.0.0.1
  become: false
  tasks:
    - include: playbook-includes/wrkbench-process.yml pass=2

- name: "Run Benchmark Pass 3"
  hosts: vcpbench-consumer*
  tasks:
    - include: playbook-includes/wrkbench-benchmark.yml pass=3 threads=1 duration=90 concurrency=200 
- name: "Get backend reqs Pass 3"
  hosts: vcpbench-backend
  tasks:
    - include: playbook-includes/wrkbench-collect.yml pass=3
- name: "Post process output Pass 3"
  connection: local
  hosts: 127.0.0.1
  become: false
  tasks:
    - include: playbook-includes/wrkbench-process.yml pass=3
