- name: "Prepare varnishservers"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Force restart of varnish"
      service: name="varnish" state="restarted" enabled="yes"
    - name: "Reset backend requests pre-benchmark"
      shell: curl -I http://localhost:8080/x-resetdummyapistatistics
- name: "Run Reference Test"
  hosts: vcpbench-consumer
  tasks:
    - name: "Warm cache"
      shell: curl -I "http://`cat /tmp/hosts/loadbalancer.cname`/reference/?content-length&max-age=6000&header-delay=100predictable-content=200000"
      register: cachewarm
    - debug: var=cachewarm.stdout_lines
    - name: "Wait for replication"
      pause: seconds=2
    - name: "Run wrk reference test (one hit url only for 10 seconds)"
      shell: /usr/local/bin/wrk -t 4 -d 10 -c 400 "http://`cat /tmp/hosts/loadbalancer.cname`/reference/?content-length&max-age=6000&header-delay=100predictable-content=200000"
      register: testresult
    - debug: var=testresult.stdout_lines
- name: "Get stats"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Dump backend requests post-reference"
      shell: curl -I http://localhost:8080/x-dumpdummyapistatistics | grep "X-Request-Counter"
      register: backendreqs
    - debug: var=backendreqs.stdout_lines
    - name: "Reset dummy-api stats"
      shell: curl -I http://localhost:8080/x-resetdummyapistatistics
- name: "Run Benchmark"
  hosts: vcpbench-consumer
  tasks:
    - name: "Run wrk varnish cache plus test (4 minutes)"
      shell: /usr/local/bin/wrk -s /tmp/multipath.lua -t 4 -d 240 -c 400 "http://`cat /tmp/hosts/loadbalancer.cname`/"
      register: testresult
    - debug: var=testresult.stdout_lines
- name: "Get backend reqs"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Dump backend requests post-benchmark"
      shell: curl -I http://localhost:8080/x-dumpdummyapistatistics | grep "X-Request-Counter"
      register: backendreqs
    - debug: var=backendreqs.stdout_lines
#    - name: "Dump varnish backend request counter post-reference"
#      command: /bin/varnishstat -1 -f MAIN.backend_req
#      register: varnishstatbackendreqs
#    - debug: var=varnishstatbackendreqs.stdout_lines
