- name: "Common setup for all hosts"
  hosts: all
  tasks:
#    - name: "Install the EPEL repo"
#      yum: name="{{ item }}" state="installed"
#      with_items:
#        - "epel-release"
    - name: "Install common tools"
      yum: name="{{ item }}" state="installed"
      with_items:
#        - "git"
        - "ansible"
#        - "wget"
#        - "vim"
    - name: "Enable tcp_tw_reuse for testing purposes"
      command: sysctl net.ipv4.tcp_tw_reuse=1
- name: "Consumer tuning"
  hosts: all
  tasks:
    - name: "Increase open files max"
      command: sysctl fs.file-max=3000000
- name: "Setup wrk benchmarks"
  hosts: vcpbench-consumer
  tasks:
    - name: "Copy wrk"
      copy: src="files/wrk" dest="/usr/local/bin/wrk" mode=ugo+rwx owner=root group=root
    - name: "Copy wrk multipath lua script"
      copy: src="files/multipath.lua" dest="/tmp/multipath.lua" mode=ugo+rwx owner=root group=root
    - name: "Copy wrk url list"
      copy: src="files/urls.txt" dest="/tmp/urls.txt" mode=ugo+rwx owner=root group=root
- name: "Setup vegeta benchmarks"
  hosts: vcpbench-consumer
  tasks:
    - name: "Copy vegeta"
      copy: src="files/vegeta" dest="/usr/local/bin/vegeta" mode=ugo+rwx owner=root group=root
    - name: "Copy vegeta target list"
      copy: src="files/targets.txt" dest="/tmp/targets.txt" mode=ugo+rwx owner=root group=root
- name: "Setup Dummy-API"
  hosts: vcpbench-varnish*
  tasks:
    - name: "Copy dummy-api binary"
      copy: src="files/dummy-api"
            dest="/usr/local/bin/dummy-api"
            mode=555 owner=root group=root
      notify:
        - "Restart dummy-api"
    - name: "Ensure the dummy-api user is present"
      user: name="dummy-api" comment="Dummy API system user"
            system="yes" state="present"
    - name: "Ensure dummy-api service script is present"
      copy: src="files/dummy-api.service"
            dest="/etc/systemd/system/dummy-api.service"
            mode=444 owner=root group=root
      notify:
        - "Restart dummy-api"
    - name: "Ensure dummy-api is running"
      service: name="dummy-api" state="running" enabled="yes"
  handlers:
    - name: "Restart dummy-api"
      service: name="dummy-api" state="restarted"
